CREATE DATABASE BlogBasic;
use BlogBasic;

CREATE TABLE usuarios (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  username VARCHAR(100) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  perfil_logo TEXT DEFAULT NULL,
  registrado_en DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  titulo VARCHAR(255) NOT NULL,
  contenido TEXT NOT NULL,
  autor_id VARCHAR(36) NOT NULL,
  creado_en DATETIME CURRENT_TIMESTAMP,
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE comentarios (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  contenido TEXT NOT NULL,
  post_id VARCHAR(36) NOT NULL,
  autor_id VARCHAR(36) NOT NULL,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE likes (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  usuario_id VARCHAR(36) NOT NULL,
  post_id VARCHAR(36) NOT NULL,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  UNIQUE (usuario_id, post_id)
);
